### ISSUE TITLE
Cannot run setup on Linux

### ISSUE THREAD

**Issue by pads** [markwallsgrove/ssh_alias_ec2#28]
I run `ec2.cli setup` and get the following error:

```
panic: user: Current not implemented on linux/amd64

goroutine 1 [running]:
main.init.1()
        /Users/mark/workspace/src/github.com/markwallsgrove/alias_ec2/main.go:40 +0x6a
main.init()
        /Users/mark/workspace/src/github.com/markwallsgrove/alias_ec2/main.go:1051 +0x401
```

**Comment by markwallsgrove** [comment]
Cross compiling from MacOSX doesn't seem to be working :( Uploaded a new release

**Comment by pads** [comment]
New release artefact works for me, thanks :+1:
